name: Test Go Service

on:
  workflow_call:
    inputs:
      service_path:
        required: true
        type: string
        description: 'Path to the service directory'
      service_name:
        required: true
        type: string
        description: 'Name of the service'
      go_version:
        required: false
        type: string
        default: '1.21'
        description: 'Go version to use'

jobs:
  test:
    name: Test ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ inputs.go_version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles(format('{0}/go.sum', inputs.service_path)) }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        working-directory: ${{ inputs.service_path }}
        run: go mod download

      - name: Run linter
        working-directory: ${{ inputs.service_path }}
        run: |
          go install golang.org/x/lint/golint@latest || true
          golint ./... || true
        continue-on-error: true

      - name: Run tests
        working-directory: ${{ inputs.service_path }}
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ${{ inputs.service_path }}/coverage.out
          flags: ${{ inputs.service_name }}
          name: ${{ inputs.service_name }}-coverage
        continue-on-error: true

